version: '3'

services:
    app:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: 'production'
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_USER: 'myuser'
            POSTGRES_PASSWORD: 'mypassword'
            POSTGRES_DB: 'mydb'
